### ISSUE TITLE
CLIP image generator 

### ISSUE THREAD

**Issue by defgsus** [openai/CLIP#108]
Much thanks you guys for developing and releasing this amazing model.

I made a tool that produces images using CLIP using similar techniques as in feature visualization. It allows defining the training pipeline in configuration files, instead of python code.

[github.com/defgsus/clipig/](https://github.com/defgsus/clipig/)

The [documentation](https://defgsus.github.io/clipig/) includes a *walk-through* with some nice examples. 

It's an early release but well documented because i'm interested in some community feedback.

**Comment by jongwook** [comment]
Great work! I think it's meaningful to have an image generator that does not rely on a separate generative model like GANs, in order to visualize what exactly CLIP learns, as opposed to what CLIP can steer along the data manifold learned by a GAN.

For the sake of keeping only the ongoing/active issues open, I'll keep this one closed for now. Thanks!
