### ISSUE TITLE
Ragarding training datasets

### ISSUE THREAD

**Issue by juhongm999** [openai/CLIP#127]
First of all, thank you for great work.
Are you planning to provide the web-crawled datasets used for training CLIP?

**Comment by jongwook** [comment]
Unfortunately, we don't have a plan to do so, in part because we don't have right to redistribute those data. As an alternative, we provide information on [the YFCC100M subset data](https://github.com/openai/CLIP/blob/main/data/yfcc100m.md) which we have shown in the paper that it can achieve comparable performance with the ResNet-50 encoder.
