### ISSUE TITLE
Why the results of cosine similarities between the corresponding image and text features may appear negative numbers and NaN?

### ISSUE THREAD

**Issue by lr19960813** [openai/CLIP#146]
I input a image and some texts in one list, then use model.(image,text) to calculate their values. Follow the instructions, the values are cosine similarities between the corresponding image and text features, times 100. 

They should all be positive numbers, but when I fine tuned clip and use the fine tuned clip model for calculations, some results are negative numbers and  even all results are NaN.  I don‘t know why this happened?

**Comment by jongwook** [comment]
While we usually observe positive cosine similarities for typical text and image inputs, they can have negative values, because it's a cosine function.

See #40, #63, #81, and #144 for tips for avoiding `NaN`s during fine-tuning. In short, converting everything to FP32 will mostly solve the problem.
