### ISSUE TITLE
Can we use `torch.nn.DataParallel ` to speed encode_image ?

### ISSUE THREAD

**Issue by mmmwhy** [openai/CLIP#36]
![image](https://user-images.githubusercontent.com/11297491/106855374-c996f180-66f7-11eb-8658-0b2f2aef7c62.png)

It seems we cannot use encode_image in DataParallel

**Comment by jongwook** [comment]
This is because `DataParallel` works by overriding the `forward()` method to launch workload in parallel. The submodule `model.visual` contains the vision model, and I expect it to work if you wrap `model.visual` instead of `model` in `nn.DataParallel`.

Another workaround would be to define an `nn.Module` that has the CLIP module as its submodule and forwards the call to the CLIP module's `encode_image()`.
