### ISSUE TITLE
YFCC-100M text filtering

### ISSUE THREAD

**Issue by hellbell** [openai/CLIP#50]
Hi, thanks for the great work!
I'm collecting YFCC-100M dataset following the paper ("After filtering to keep only images with natural language titles and/or descriptions in English, the dataset shrunk by a factor of 6 to only 15 million photos.").
Could you share the way to filter out the non-natural language texts of YFCC-100M?

**Comment by jongwook** [comment]
We used a third-party language detection library for it. For easier reproducibility, we uploaded the line numbers (the first column of the YFCC100M dataset TSV) corresponding to the filtered subset: https://github.com/openai/CLIP/blob/data/yfcc100m_subset_line_numbers.npy.bz2

**Comment by hellbell** [comment]
@jongwook Great, Thanks!

**Comment by ModMorph** [comment]
Hi @jongwook, I can find the YFCC100M dataset images on Amazon commons https://registry.opendata.aws/multimedia-commons/ but the TSV dataset I haven't been able to find. It seems to have been removed from Yahoo, google links go to spammer sites. Any suggestions how to find it? 

Are there any other examples of lists of specific parts of public datasaets you can share that CLIP was trained on, along with data that was included/excluded? Trying compare against data that the CLIP model HASN'T seen, and find dataset CLIP has seen and for sure hasn't seen. I guess I can find new images/metadata after x date, but wanted similar datasets so that something like higher camera resolutions for newer data didn't alter my results.

Many thanks, great work!

**Comment by jongwook** [comment]
Hi @ModMorph, I just uploaded [yfcc100m.md](https://github.com/openai/CLIP/blob/main/data/yfcc100m.md) that points to a TSV file containing the line number, the photo identifier, and the photo hash corresponding to the YFCC100M subset.

It looks like the AWS Open Data website used the photo hash data from the TSV file, which was the third column of the table. They used 2-level prefixes so that a photo whose hash starts with `abcdef...` is located under `images/abc/def/`.

So you can be sure that CLIP has seen these images, and it hasn't seen anything newly taken in 2021.

**Comment by ReneTCAd** [comment]
> Hi, thanks for the great work! I'm collecting YFCC-100M dataset following the paper ("After filtering to keep only images with natural language titles and/or descriptions in English, the dataset shrunk by a factor of 6 to only 15 million photos."). Could you share the way to filter out the non-natural language texts of YFCC-100M?

Hi, I am curious about the specific filtering rule. With the given line number, which text should I use, the title or the description?

**Comment by g-luo** [comment]
@jongwook I was wondering if you had the metadata file for YFCC-100M, which also contains camera id, latitude, longitude and all the hashes? As mentioned above, this data is now difficult to find.

**Comment by g-luo** [comment]
Never mind; found at: https://multimedia-commons.s3-us-west-2.amazonaws.com/tools/etc/yfcc100m_dataset.sql

**Comment by SankyStuff** [comment]
> Never mind; found at: https://multimedia-commons.s3-us-west-2.amazonaws.com/tools/etc/yfcc100m_dataset.sql

@g-luo I am pretty new to handling this big of a file. How did you open/view it?
