### ISSUE TITLE
Pretrained ViT-B/16?

### ISSUE THREAD

**Issue by LiJunnan1992** [openai/CLIP#61]
Hi, may I know if you have plans to release pretrained ViT-B/16? Thanks!

**Comment by jongwook** [comment]
We are carefully continuing our research in a similar manner to what we did for GPT-2 [1], but unfortunately, we haven't yet arrived at a conclusion as to whether/when to release the next set of models. I'll close this issue since #2 can serve the same purpose.

[1] I. Solaiman et al. (2019) [Release Strategies and the Social Impacts of Language Models](https://arxiv.org/abs/1908.09203)
