### ISSUE TITLE
Does the tokenizer support Chinese?

### ISSUE THREAD

**Issue by zhanxlin** [openai/CLIP#7]
Hello, does the tokenizer support Chinese?

**Comment by jongwook** [comment]
Hello!

The tokenizer is based on [byte-pair encoding](https://en.wikipedia.org/wiki/Byte_pair_encoding) and is able to tokenize any valid UTF-8 string, but it is not recommended to use this tokenizer for non-English sentences since its vocabulary is primarily based on English. Furthermore, CLIP models are trained with mostly English data, so we don't expect particularly good performance from CLIP with non-English text inputs. Multilingual CLIP would be an interesting future work.

**Comment by ruby0101** [comment]
Hi, @jongwook, "CLIP models are trained with mostly English data". So can it be re-trained with a new image text pair dataset in other languages?

**Comment by jongwook** [comment]
Yes; I presume it'll need to train from scratch (or at least the text encoder) in that case.

**Comment by datalee** [comment]
Multilingual CLIP 666

**Comment by yangapku** [comment]
Hi, maybe you can refer to this repo! https://github.com/OFA-Sys/Chinese-CLIP

**Comment by andrewqianpublic** [comment]
The tokenization method I came up with involves streaming. The way Chinese characters are designed is that any sequence of bytes making up the Chinese characters will not form a valid char that can be decoded. That is, no valid char is a prefix of any Chinese char or likely any char from nay language. In this way, you can simply attempt to decode a sequence of bytes (break down all generated chars into bytes, append to list, convert using bytearray, then attempt decode), and if that fails, simply wait for the next set of new chars until you get enough to decode into a valid character. You can then stream it. This seems to work consistently. Hope this helps whoever comes across this.
