### ISSUE TITLE
Layer Norm before Residual 

### ISSUE THREAD

**Issue by skull8888888** [openai/CLIP#91]
Hello, I noticed that on line 186 in `model.py` you put `layer norm` before `MultiHeadAttention` and Residual, as opposed to putting Layer Norm after Residual as described in the original Transformer paper.

```
def forward(self, x: torch.Tensor):
    x = x + self.attention(self.ln_1(x))
    x = x + self.mlp(self.ln_2(x))
    return x
```

In my research I found this [paper](https://openreview.net/pdf?id=B1x8anVFPr) which argues that such configuration improves convergence and removes the need for careful warmup. 

In my experiment when I used your implementation of Transformer Block for seq2seq model 1 layer works pretty nice, however when I stuck 2 layers performance significantly degrades. 

So my questions are: What is the reasoning behind it? And how to make it work with stacked layers?

**Comment by jongwook** [comment]
The linked paper shows some reasoning behind using normalizations in the residual branch as opposed to the main trunk. One intuition is that keeping an identity mapping flow helps stabilize the training, as suggested by [He et al. (2016)](https://arxiv.org/abs/1603.05027), as opposed to going through multiple layer normalization ops proportional to the depth. This approach is adopted in most of OpenAI models since GPT-2, as outlined in [page 4, column 2 of the GPT-2 paper](https://cdn.openai.com/papers/Learning_Transferable_Visual_Models_From_Natural_Language_Supervision.pdf) and [Figure 8d of the Jukebox paper](https://arxiv.org/pdf/2005.00341.pdf).
